// <auto-generated />
namespace GMUAdmissionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class noenrolldecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noenrolldecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201704100212162_noenrolldecision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
